name: Test PromptFlow  
on:  
  push:  
    branches:  
      - main  
jobs:  
  build-linux:  
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v4  
      
    - name: Set up Python 3.9  
      uses: actions/setup-python@v3  
      with:  
        python-version: '3.9'  
      
    - name: Add conda to system path  
      run: |  
        # $CONDA is an environment variable pointing to the root of the miniconda directory  
        echo "$CONDA/bin" >> $GITHUB_PATH  
      
    - name: List files and folders  
      run: |  
        ls -R . -ll  
      
    - name: Install dependencies and initialize conda  
      run: |  
        # Initialize conda by sourcing directly  
        source $CONDA/etc/profile.d/conda.sh  
          
        # Update conda environment  
        conda env update --file dependencies.yml --name promptflow  
      
    - name: Lint with flake8  
      run: |  
        # Initialize conda by sourcing directly  
        source $CONDA/etc/profile.d/conda.sh  
          
        # Activate the environment  
        conda activate promptflow  
          
        # Install flake8  
        pip install flake8  
          
        # Lint the code  
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


    - name: Create a PromptFlow Connection  
      run: |  
        # Initialize conda by sourcing directly  
        source $CONDA/etc/profile.d/conda.sh  
          
        # Activate the environment  
        conda activate promptflow  
          
        # Create and list PromptFlow connection  
        pf connection create --file ./azure_openai.yml --set api_key="73f07aee325f4c2dbc4b3edba631d738" api_base="https://mmoaiswc-01.openai.azure.com/"  
        pf connection list  
        pf connection show -n open_ai_connection  
